ignore_projects: []
issues_template_configs:
- panel_name: " \U0001F41E 上报 BUG (Report bug)"
  file_name: bug
  panel_description: 烦请您帮助我们进步(Create a report to help us improve).
  pull_request_prefix: '[Bug]: '
  pull_request_labels:
  - name: bug
    description: Something isn't working
    color: d73a4a
- panel_name: " \U0001F4A1 新的想法 (Feature request)"
  file_name: feature
  panel_description: 我知道您有一个比较赞的想法想和我说 (Suggest an idea for this project).
  pull_request_prefix: '[Feature]:'
  pull_request_labels:
  - name: enhancement
    description: New feature or request
    color: a2eeef
- panel_name: " \U0001F4E3 和作者进行灵魂沟通 (Feedback)"
  file_name: feedback
  panel_description: 来聊聊咱这个库好在哪里,差在哪里和你的期待在哪里 (Give us general feedback about the repository).
  pull_request_prefix: '[Feedback]:'
  pull_request_labels:
  - name: feedback
    description: Something want to say
    color: d4c5f9
action:
  folded_projects: 
  global_labels: 
  projects:
  - id: 1
    is_ignored: false
    is_folded: false
    relative_path: ''
    project_name: Action
    package_name: ''
    project_folder: .github
    labels: 
    dependency_config:
      type: github-actions
      interval: monthly
      commit_prefix: '[DEPENDENCY ACTION]'
      special_time: 05:00
      special_time_zone: Asia/Harbin
      labels:
      - name: dependencies
        description: 有依赖需要升级
        color: 4E04B0
      ignore: 
  - id: 2
    is_ignored: false
    is_folded: false
    relative_path: ''
    project_name: Action Workflow
    package_name: ''
    project_folder: .github/workflows
    labels: 
    dependency_config:
      type: github-actions
      interval: monthly
      commit_prefix: '[DEPENDENCY ACTION]'
      special_time: 05:00
      special_time_zone: Asia/Harbin
      labels:
      - name: dependencies
        description: 有依赖需要升级
        color: 4E04B0
      ignore: 
samples:
  folded_projects: []
  global_labels:
  - name: pr_samples
    description: 此次提交包含 [案例工程] 相关的改动.
    color: 68E0F8
  projects:
  - id: B81C35F3-3471-4DFA-BA54-FD72A8BCCE28
    is_ignored: false
    is_folded: false
    relative_path: samples/Sample1/Sample1.csproj
    project_name: Sample1
    package_name: Sample1
    project_folder: samples/Sample1
    labels: 
    dependency_config:
      type: nuget
      interval: monthly
      commit_prefix: '[DEPENDENCY SAMPLE]'
      special_time: 05:00
      special_time_zone: Asia/Harbin
      labels:
      - name: dependencies
        description: 有依赖需要升级
        color: 4E04B0
      ignore: 
src:
  folded_projects: []
  global_labels:
  - name: pr_src
    description: 此次提交包含 [源码工程] 相关的改动.
    color: 68E0F8
  projects:
  - using_output: 
    id: 131F5C66-58B1-4D48-BCC0-4E9CEFE1ADFD
    is_ignored: false
    is_folded: false
    relative_path: src/Project/Project.csproj
    project_name: Project
    package_name: Project
    project_folder: src/Project
    labels: 
    dependency_config:
      type: nuget
      interval: daily
      commit_prefix: '[DEPENDENCY SRC]'
      special_time: 
      special_time_zone: 
      labels:
      - name: dependencies
        description: 有依赖需要升级
        color: 4E04B0
      ignore: 
test:
  folded_projects: []
  global_labels:
  - name: pr_test
    description: 此次提交包含 [测试工程] 相关的改动.
    color: 68E0F8
  projects:
  - trigger_pull_request_test: true
    trigger_codecov: true
    id: D66DF63E-DA0E-4DDF-9655-0A7E23B29082
    is_ignored: false
    is_folded: false
    relative_path: test/ut/UnitTestProject/UnitTestProject.csproj
    project_name: UnitTestProject
    package_name: UnitTestProject
    project_folder: test/ut/UnitTestProject
    labels: 
    dependency_config:
      type: nuget
      interval: weekly
      commit_prefix: '[DEPENDENCY TEST]'
      special_time: 
      special_time_zone: 
      labels:
      - name: dependencies
        description: 有依赖需要升级
        color: 4E04B0
      ignore: 
workflow:
  folded_projects:
  - test/workflow/Workflow.Nuget.Publish/Workflow.Nuget.Publish.csproj
  - test/workflow/Github.NET.Sdk/Github.NET.Sdk.csproj
  - test/workflow/Workflow.Initialization/Workflow.Initialization.csproj
  - test/workflow/Workflow.Runner/Workflow.Runner.csproj
  - test/workflow/Solution.NET.Sdk/Solution.NET.Sdk.csproj
  - test/workflow/Github.NMSAction.NET.Sdk/Github.NMSAction.NET.Sdk.csproj
  global_labels: 
  projects: []
