name: 🤝 入组申请
description: 希望能加入这个组织,为组织做出贡献.
title: "[Invite]:"
labels: ["invite"]
body:
  - type: markdown
    attributes:
      value: |
        ### 尊敬的组织成员:
        你们好,我希望能够成为该组织中的一员,为组织做出贡献,我承诺遵守以下组织开发原则:
        - 深度学习或贡献某个开源项目.
        - 不故意无理由的诋毁竞品库.
        - 不向自己参与的项目提交恶意或反人类的代码及注释.
        - 遵守开发安全准则,PR 中不得出现敏感词汇及 APP 密钥等.
        - 谨言慎行,不触犯国家法律.
        - 不以组织及他人名义引战挑事.
        - 遵守组织颁布的开发规定.
        - 积极响应需求/问题/代码审阅等任务.
        - 以平和的语气及文字接收或提出建议及意见.
        <br/>
        此致敬礼!
        <br/>

  - type: input
    id: contact
    attributes:
      label: 📞 我的联系方式(Contact Details).
      description: 
      placeholder: ex. email@example.com
    validations:
      required: false
