name: UT Test From PR

on:
   pull_request:
     types: [opened]
     branches:
       - dev**

jobs:
    
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: 🔨 Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          3.1.x
          5.0.x
          6.0.x
          7.0.x

    - name: 🚦 UnitTestProject UT Test
      run: dotnet test './test/ut/UnitTestProject' --nologo -c Release -l "trx;LogFileName=UnitTestProject.trx" --results-directory "TestResults"

    - name: Upload dotnet test results
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-results
        path: TestResults

    - name: Create Report
      uses: dorny/test-reporter@v1.6.0
      with:
        name: XUnit Reporter                  # Name of the check run which will be created
        path: 'TestResults/*.trx'             # Path to test results (inside artifact .zip)
        reporter: dotnet-trx                  # Format of test results
        token: ${{ secrets.REPO_GITHUB_TOKEN }}
