name: UT Test From PR

on:
   pull_request:
     types: [opened]
     branches:
       - dev**

jobs:
    
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - name: 🔨 Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.0.x


    - name: 🚦 UnitTestProject UT Test
      run: dotnet test './test/ut/UnitTestProject' --nologo -c Release -l "trx;LogFileName=UnitTestProject.xml" --results-directory "./testlogs/"


    - name: Create Report
      uses: dorny/test-reporter@v1.6.0
      with:
        name: Xunit Reporter                  # Name of the check run which will be created
        path: 'testlogs/*.xml'              # Path to test results (inside artifact .zip)
        reporter: dotnet-trx                  # Format of test results
        token: ${{ secrets.REPO_GITHUB_TOKEN }}
